In [43]:
#pip install dash-ag-grid

In [44]:
import requests
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [87]:
wages = pd.read_csv("./City_of_Seattle_Wage_Data_20260402.csv")

In [46]:
wages.head()

,Department,Last Name,First Name,Job Title,Hourly Rate
0,Seattle Police Department,Aagard,Lori,Executive 4,$150.43
1,Seattle City Light,Aaltonen,Evan,Powerline Clear Tree Trimmer,$61.52
2,Seattle Public Utilities,Aar,Abdimallik,"Civil Engineering Specialist,Senior",$70.35
3,Seattle Department of Transportation,Abad,Abigail,Administrative Specialist II-BU,$41.31
4,Human Services,Aba-Husain,Adam,"Grants and Contracts Specialist,Senior",$50.33

In [47]:
wages.columns

Index(['Department', 'Last Name', 'First Name', 'Job Title', 'Hourly Rate '], dtype='str')

In [96]:
wages = wages.rename(columns={"Hourly Rate ": "Hourly Rate"})
#wages = wages.rename(str.lower, axis=1)

In [97]:
wages.columns

Index(['Department', 'Last Name', 'First Name', 'Job Title', 'Hourly Rate'], dtype='str')

In [85]:
wages.dtypes

Department             str
Last Name              str
First Name             str
Job Title              str
Hourly Rate        float64
Salary Estimate    float64
Name                   str
dtype: object

In [101]:
wages['Hourly Rate'] = wages['Hourly Rate'].str.strip("$")
wages['Hourly Rate'] = wages['Hourly Rate'].astype("float64")
wages['Salary Estimate'] = wages['Hourly Rate'] * 2080

In [102]:
wages.dtypes

Department             str
Last Name              str
First Name             str
Job Title              str
Hourly Rate        float64
Salary Estimate    float64
dtype: object

In [103]:
wages.columns

Index(['Department', 'Last Name', 'First Name', 'Job Title', 'Hourly Rate',
       'Salary Estimate'],
      dtype='str')

In [104]:
wages.sort_values(by=["Hourly Rate"], ascending=False)

,Department,Last Name,First Name,Job Title,Hourly Rate,Salary Estimate
7334,Seattle City Light,Lindell,Dawn,City Light General Manager & CEO,254.79,529963.2
8245,Seattle City Light,McLerran,Dennis,"Electric Utility Executive 3,Officer",186.65,388232.0
7114,Seattle Public Utilities,Lee,Andrew,SPU General Manager & CEO,179.55,373464.0
11086,Seattle Fire Department,Scoggins,Harold,Fire Chief,179.55,373464.0
793,Seattle Police Department,Barnes,Shon,Seattle Police Chief,179.54,373443.2
...,...,...,...,...,...,...
3562,Parks and Recreation Department,Edo,Abdiaziz,High School Intern,21.51,44740.8
3152,Parks and Recreation Department,Desierto,Desmond,High School Intern,21.51,44740.8
7737,Parks and Recreation Department,Makelfa,Marsha,High School Intern,21.51,44740.8
10211,Parks and Recreation Department,Randolph,Nicholas,Work Training Enrollee,21.51,44740.8
30,Parks and Recreation Department,Abdulkadir,Majid,High School Intern,21.51,44740.8

In [105]:
wages.groupby('Department').count()

,Last Name,First Name,Job Title,Hourly Rate,Salary Estimate
Department,,,,,
City Auditor's Office,7,7,7,7,7
City Budget Office,36,36,36,36,36
Civil Rights Office,37,37,37,37,37
Civil Service Commissions,10,10,10,10,10
Community Police Commission,10,10,10,10,10
Community Safety and Communication Center,198,198,198,198,198
Construction and Inspections,410,410,410,410,410
Economic and Revenue Forecasts,2,2,2,2,2
Education and Early Learning,119,119,119,119,119
Emergency Management Office,13,13,13,13,13
Employees Retirement System,37,37,37,37,37
Ethics and Elections Commissions,11,11,11,11,11
Finance and Administrative Service,575,575,575,575,575
Hearing Examiner,5,5,5,5,5
Housing Office,63,63,63,63,63
Human Resources,88,88,88,88,88
Human Services,467,467,467,467,467
Immigration and Refugee Affairs,12,12,12,12,12
Information Technology,571,571,571,571,571
Intergovernmental Relations,8,8,8,8,8
Law Department,211,211,211,211,211
Legislative Department,98,98,98,98,98
Mayor's Office,47,47,47,47,47
Neighborhoods,64,64,64,64,64
Office of Arts and Culture,55,55,55,55,55
Office of Economic Development and Special Events Office,51,51,51,51,51
Office of Labor Standards,31,31,31,31,31
Office of the Employee Ombud,7,7,7,7,7
Office of the Inspector General for Public Safety,22,22,22,22,22
Parks and Recreation Department,1764,1764,1764,1764,1764
Planning and Community Office,50,50,50,50,50
Police Relief and Pension,4,4,4,4,4
Seattle Center,570,570,570,570,570
Seattle City Light,1802,1802,1802,1802,1802
Seattle Department of Transportation,1167,1167,1167,1167,1167
Seattle Fire Department,1138,1138,1138,1138,1138
Seattle Municipal Courts,211,211,211,211,211
Seattle Police Department,1634,1634,1634,1634,1634
Seattle Public Library,650,650,650,650,650
Seattle Public Utilities,1549,1549,1549,1549,1549
Sustainability and Environment,60,60,60,60,60

In [106]:
avg_wage = wages[['Department','Hourly Rate','Salary Estimate']].groupby(['Department']).mean().sort_values('Hourly Rate', ascending=False)

avg_wage

,Hourly Rate,Salary Estimate
Department,,
Police Relief and Pension,89.070000,185265.600000
Mayor's Office,85.282128,177386.825532
Intergovernmental Relations,78.227500,162713.200000
City Budget Office,77.950556,162137.155556
City Auditor's Office,76.818571,159782.628571
Information Technology,76.150315,158392.655692
Economic and Revenue Forecasts,74.450000,154856.000000
Community Police Commission,71.500000,148720.000000
Hearing Examiner,69.742000,145063.360000
Seattle Police Department,68.983268,143485.197552
Emergency Management Office,68.983077,143484.800000
Law Department,68.627962,142746.161137
Employees Retirement System,68.488108,142455.264865
Civil Service Commissions,68.069000,141583.520000
Human Resources,67.597841,140603.509091
Seattle City Light,67.539073,140481.272364
Ethics and Elections Commissions,65.704545,136665.454545
Office of the Employee Ombud,65.185714,135586.285714
Construction and Inspections,64.993415,135186.302439
Planning and Community Office,63.965800,133048.864000
Office of the Inspector General for Public Safety,63.667273,132427.927273
Legislative Department,63.534694,132152.163265
Civil Rights Office,63.457568,131991.740541
Office of Economic Development and Special Events Office,63.435098,131945.003922
Office of Labor Standards,63.228710,131515.716129
Sustainability and Environment,62.439333,129873.813333
Housing Office,62.319841,129625.269841
Neighborhoods,61.454531,127825.425000
Immigration and Refugee Affairs,61.189167,127273.466667
Seattle Department of Transportation,59.984679,124768.131620
Education and Early Learning,59.346050,123439.784874
Finance and Administrative Service,58.819183,122343.899826
Seattle Public Utilities,58.679651,122053.674887
Seattle Fire Department,57.081924,118730.402812
Seattle Municipal Courts,56.083270,116653.201896
Office of Arts and Culture,55.099636,114607.243636
Human Services,54.720814,113819.292505
Community Safety and Communication Center,52.753485,109727.248485
Seattle Public Library,45.231031,94080.544000
Seattle Center,41.541561,86406.447719
Parks and Recreation Department,39.799246,82782.431746

In [107]:
wages['Job Title'].unique().shape

(1181,)

In [108]:
over200k = wages[wages['Salary Estimate'] > 200000]

In [ ]:
#px.scatter(wages, x='hourly rate',y='department', color='department')

In [109]:
wages.groupby('Department').count().sort_values('Last Name', ascending=False)

,Last Name,First Name,Job Title,Hourly Rate,Salary Estimate
Department,,,,,
Seattle City Light,1802,1802,1802,1802,1802
Parks and Recreation Department,1764,1764,1764,1764,1764
Seattle Police Department,1634,1634,1634,1634,1634
Seattle Public Utilities,1549,1549,1549,1549,1549
Seattle Department of Transportation,1167,1167,1167,1167,1167
Seattle Fire Department,1138,1138,1138,1138,1138
Seattle Public Library,650,650,650,650,650
Finance and Administrative Service,575,575,575,575,575
Information Technology,571,571,571,571,571
Seattle Center,570,570,570,570,570
Human Services,467,467,467,467,467
Construction and Inspections,410,410,410,410,410
Law Department,211,211,211,211,211
Seattle Municipal Courts,211,211,211,211,211
Community Safety and Communication Center,198,198,198,198,198
Education and Early Learning,119,119,119,119,119
Legislative Department,98,98,98,98,98
Human Resources,88,88,88,88,88
Neighborhoods,64,64,64,64,64
Housing Office,63,63,63,63,63
Sustainability and Environment,60,60,60,60,60
Office of Arts and Culture,55,55,55,55,55
Office of Economic Development and Special Events Office,51,51,51,51,51
Planning and Community Office,50,50,50,50,50
Mayor's Office,47,47,47,47,47
Employees Retirement System,37,37,37,37,37
Civil Rights Office,37,37,37,37,37
City Budget Office,36,36,36,36,36
Office of Labor Standards,31,31,31,31,31
Office of the Inspector General for Public Safety,22,22,22,22,22
Emergency Management Office,13,13,13,13,13
Immigration and Refugee Affairs,12,12,12,12,12
Ethics and Elections Commissions,11,11,11,11,11
Civil Service Commissions,10,10,10,10,10
Community Police Commission,10,10,10,10,10
Intergovernmental Relations,8,8,8,8,8
City Auditor's Office,7,7,7,7,7
Office of the Employee Ombud,7,7,7,7,7
Hearing Examiner,5,5,5,5,5
Police Relief and Pension,4,4,4,4,4
Economic and Revenue Forecasts,2,2,2,2,2

In [110]:
wages['Name'] = wages['First Name'] + ' ' + wages['Last Name']
wages.head()

,Department,Last Name,First Name,Job Title,Hourly Rate,Salary Estimate,Name
0,Seattle Police Department,Aagard,Lori,Executive 4,150.43,312894.4,Lori Aagard
1,Seattle City Light,Aaltonen,Evan,Powerline Clear Tree Trimmer,61.52,127961.6,Evan Aaltonen
2,Seattle Public Utilities,Aar,Abdimallik,"Civil Engineering Specialist,Senior",70.35,146328.0,Abdimallik Aar
3,Seattle Department of Transportation,Abad,Abigail,Administrative Specialist II-BU,41.31,85924.8,Abigail Abad
4,Human Services,Aba-Husain,Adam,"Grants and Contracts Specialist,Senior",50.33,104686.4,Adam Aba-Husain

,Department,Last Name,First Name,Job Title,Salary Estimate,Name
Hourly Rate,,,,,,
26.92,599,599,599,599,599,599
76.46,373,373,373,373,373,373
37.95,292,292,292,292,292,292
55.19,246,246,246,246,246,246
77.36,206,206,206,206,206,206
...,...,...,...,...,...,...
166.21,1,1,1,1,1,1
169.57,1,1,1,1,1,1
170.28,1,1,1,1,1,1
174.36,1,1,1,1,1,1
126.35,1,1,1,1,1,1

In [115]:
wages['Hourly Rate'].describe()

count    13864.000000
mean        58.526846
std         20.541617
min         21.510000
25%         42.950000
50%         55.795000
75%         74.422500
max        254.790000
Name: Hourly Rate, dtype: float64

In [116]:
wages.sort_values('Hourly Rate', ascending=False)

,Department,Last Name,First Name,Job Title,Hourly Rate,Salary Estimate,Name
7334,Seattle City Light,Lindell,Dawn,City Light General Manager & CEO,254.79,529963.2,Dawn Lindell
8245,Seattle City Light,McLerran,Dennis,"Electric Utility Executive 3,Officer",186.65,388232.0,Dennis McLerran
7114,Seattle Public Utilities,Lee,Andrew,SPU General Manager & CEO,179.55,373464.0,Andrew Lee
11086,Seattle Fire Department,Scoggins,Harold,Fire Chief,179.55,373464.0,Harold Scoggins
793,Seattle Police Department,Barnes,Shon,Seattle Police Chief,179.54,373443.2,Shon Barnes
...,...,...,...,...,...,...,...
3562,Parks and Recreation Department,Edo,Abdiaziz,High School Intern,21.51,44740.8,Abdiaziz Edo
3152,Parks and Recreation Department,Desierto,Desmond,High School Intern,21.51,44740.8,Desmond Desierto
7737,Parks and Recreation Department,Makelfa,Marsha,High School Intern,21.51,44740.8,Marsha Makelfa
10211,Parks and Recreation Department,Randolph,Nicholas,Work Training Enrollee,21.51,44740.8,Nicholas Randolph
30,Parks and Recreation Department,Abdulkadir,Majid,High School Intern,21.51,44740.8,Majid Abdulkadir

In [124]:
wage_group = wages.groupby('Hourly Rate').count().sort_values('Department',ascending=False)

range from 21.51-254.79

In [125]:
wage_group

,Department,Last Name,First Name,Job Title,Salary Estimate,Name
Hourly Rate,,,,,,
26.92,599,599,599,599,599,599
76.46,373,373,373,373,373,373
37.95,292,292,292,292,292,292
55.19,246,246,246,246,246,246
77.36,206,206,206,206,206,206
...,...,...,...,...,...,...
166.21,1,1,1,1,1,1
169.57,1,1,1,1,1,1
170.28,1,1,1,1,1,1
174.36,1,1,1,1,1,1
126.35,1,1,1,1,1,1

In [135]:
rng=np.random.default_rng()

In [140]:
jitter_coords = wage_group.apply(lambda x: rng.normal(loc=0,scale=.3,size=x['Department']), axis=1)

In [141]:
def add_jitter(df, bucket_col, jitter_col='jitter', scale=0.1):
    """
    Adds normally-distributed jitter centered at 0.
    Points alone in their bucket get 0.
    """
    counts = df[bucket_col].map(df[bucket_col].value_counts())
    jitter = np.random.normal(loc=0, scale=scale, size=len(df))
    jitter[counts == 1] = 0
    df[jitter_col] = jitter
    return df

In [143]:
jittered = add_jitter(wages, 'Department')

In [150]:
jittered.to_csv('jittered.csv')

In [1]:
%load_ext sql

In [16]:
from sqlalchemy import create_engine

In [17]:
eng = create_engine("sqlite:///wages.db")

In [18]:
%sql sqlite:///wages.db

Connecting and switching to connection 'sqlite:///wages.db'

In [40]:
%%sql 
SELECT * FROM wages

Running query in 'sqlite:///wages.db'

+--------+--------------------------------------+--------------------+-------------+---------------------------------------------+-------------+--------------------+------------------------------+------------------------+
| field1 |              Department              |     Last Name      |  First Name |                  Job Title                  | Hourly Rate |  Salary Estimate   |             Name             |         jitter         |
+--------+--------------------------------------+--------------------+-------------+---------------------------------------------+-------------+--------------------+------------------------------+------------------------+
|   0    |      Seattle Police Department       |       Aagard       |     Lori    |                 Executive 4                 |    150.43   |      312894.4      |         Lori Aagard          |  0.023083682267714123  |
|   1    |          Seattle City Light          |      Aaltonen      |     Evan    |         Powerline Clear Tree Trimmer        |    61.52    |      127961.6      |        Evan Aaltonen         |  0.02957159642412648   |
|   2    |       Seattle Public Utilities       |        Aar         |  Abdimallik |     Civil Engineering Specialist,Senior     |    70.35    |      146328.0      |        Abdimallik Aar        |  -0.17775167947629217  |
|   3    | Seattle Department of Transportation |        Abad        |   Abigail   |       Administrative Specialist II-BU       |    41.31    |      85924.8       |         Abigail Abad         | -0.040672376118105605  |
|   4    |            Human Services            |     Aba-Husain     |     Adam    |    Grants and Contracts Specialist,Senior   |    50.33    |      104686.4      |       Adam Aba-Husain        |  0.016365260746455713  |
|   5    |   Parks and Recreation Department    |        Aban        |   Eduardo   |            Civil Engineer,Senior            |    87.31    | 181604.80000000002 |         Eduardo Aban         |  0.05968000184295072   |
|   6    |          Seattle City Light          |       Abarca       |    Fredy    |          Power Structures Mechanic          |    54.13    | 112590.40000000001 |         Fredy Abarca         | -0.020956113662641603  |
|   7    |      Seattle Police Department       |     Abasbarzy      |    Maryam   |              Police Officer-BWV             |    67.15    |      139672.0      |       Maryam Abasbarzy       | -0.0054088056455666375 |
|   8    |      Office of Arts and Culture      |       Abatan       |   Adetola   |          Arts Program Specialist BU         |    46.43    |      96574.4       |        Adetola Abatan        | -0.017932439432762223  |
|   9    |        Seattle Public Library        |      Abatayo       |  Cyril John |             Library Associate II            |    32.34    | 67267.20000000001  |      Cyril John Abatayo      | -0.014559339448688886  |
|   10   |       Seattle Public Utilities       |      Abatayo       |    Adora    |      Utility Account Representative II      |    44.92    |      93433.6       |        Adora Abatayo         |  0.10351850405798038   |
|   11   |        Seattle Public Library        |      Abateneh      |    Nebiyu   |            Library Technician II            |    36.27    |      75441.6       |       Nebiyu Abateneh        |  -0.09624517153709611  |
|   12   |            Seattle Center            |        Abay        |   Freweini  |              Parking Attendant              |    26.92    | 55993.600000000006 |        Freweini Abay         |  0.19184869778841007   |
|   13   |       Seattle Public Utilities       | Abayagunawardhana  |  Chathurika |             Accountant Principal            |    60.55    |      125944.0      | Chathurika Abayagunawardhana |  0.03964404417144102   |
|   14   | Seattle Department of Transportation |      Abayneh       | Haregewoyen |               Engineering Aide              |    42.07    |      87505.6       |     Haregewoyen Abayneh      |  -0.03373205900796972  |
|   15   |          Seattle City Light          |       Abbott       |    Jeremy   |        Electrical Work Rev Crew Chief       |    87.02    |      181001.6      |        Jeremy Abbott         |  -0.05624084842063537  |
|   16   |        Information Technology        |       Abbott       |     Paul    |   Information Technology Professional B BU  |    75.39    |      156811.2      |         Paul Abbott          |   0.1191873168458356   |
|   17   |       Seattle Municipal Courts       |       Abdala       |    Uweisi   |               Finance Analyst               |    50.98    |      106038.4      |        Uweisi Abdala         | -0.041907565786700934  |
|   18   |     Education and Early Learning     | Abdelrahmanabdalla |    Salma    |     Early Education Specialist,Senior BU    |    52.18    |      108534.4      |   Salma Abdelrahmanabdalla   |  -0.25978716469034774  |
|   19   | Seattle Department of Transportation |     Abdelsayed     |     Amy     |          Strategic Advisor 1 - OoC          |    63.84    |      132787.2      |        Amy Abdelsayed        |  -0.05861827046158315  |
|   20   |            Human Services            |        Abdi        |   Mohamed   |                  Counselor                  |    48.58    |      101046.4      |         Mohamed Abdi         |  -0.1602377958231905   |
|   21   |      Office of Labor Standards       |        Abdi        |    Ahmed    |    Planning and Development Specialist II   |    57.31    |      119204.8      |          Ahmed Abdi          | -0.021507268974507266  |
|   22   |            Human Services            |        Abdi        |     Ardo    |                  Counselor                  |    50.42    |      104873.6      |          Ardo Abdi           | -0.011296526531848795  |
|   23   |       Seattle Public Utilities       |        Abdi        |    Hodan    |     Operations Response Center Operator     |    38.66    | 80412.79999999999  |          Hodan Abdi          |  0.04712792273114362   |
|   24   |   Parks and Recreation Department    |     Abdirahman     |   Mohamed   |             Recreation Attendant            |    26.92    | 55993.600000000006 |      Mohamed Abdirahman      |  0.18104141719972505   |
|   25   |            Human Services            |      Abdissa       |    Yesuf    |    Grants and Contracts Specialist,Senior   |    50.33    |      104686.4      |        Yesuf Abdissa         |  -0.09745744334462733  |
|   26   |        Seattle Public Library        |     Abdorohman     |   Sakyroh   |            Operations Supervisor            |     59.2    |      123136.0      |      Sakyroh Abdorohman      |  0.034468750448003516  |
|   27   |        Information Technology        |       Abdul        |    Naveed   |   Information Technology Professional B BU  |    78.41    |      163092.8      |         Naveed Abdul         |  -0.02674808562909536  |
|   28   |       Seattle Public Utilities       |     Abdulhamid     |  Abdulaziz  |       Utility Account Representative I      |    37.06    |      77084.8       |     Abdulaziz Abdulhamid     |  0.04431983354889812   |
|   29   |   Parks and Recreation Department    |     Abdulkadir     |   Shabazz   |    Planning and Development Specialist II   |    51.24    |      106579.2      |      Shabazz Abdulkadir      |  0.19926154599993368   |
|   30   |   Parks and Recreation Department    |     Abdulkadir     |    Majid    |              High School Intern             |    21.51    |      44740.8       |       Majid Abdulkadir       |  0.07880538617065223   |
|   31   |   Parks and Recreation Department    |     Abdulkadir     |   Sabrina   |              Cooperative Intern             |    22.56    | 46924.799999999996 |      Sabrina Abdulkadir      |  -0.2026987873384556   |
|   32   |   Parks and Recreation Department    |     Abdulkarim     |   Mariyam   |             Recreation Attendant            |    26.92    | 55993.600000000006 |      Mariyam Abdulkarim      |  -0.0144311767390701   |
|   33   |       Seattle Public Utilities       |     Abdullahi      |    Ahmed    |   Information Technology Professional B BU  |    69.78    |      145142.4      |       Ahmed Abdullahi        |  -0.16416528368109373  |
|   34   |   Parks and Recreation Department    |     Abdullahi      |    Fartun   |             Recreation Attendant            |    26.92    | 55993.600000000006 |       Fartun Abdullahi       |  0.011388258036273722  |
|   35   |   Parks and Recreation Department    |     Abdullahi      |    Maryan   |             Recreation Attendant            |    26.92    | 55993.600000000006 |       Maryan Abdullahi       |  -0.09077743851639213  |
|   36   |         Civil Rights Office          |       Abebe        |   Medhanit  | Strategic Advisor 1, General Government-L17 |    66.79    |      138923.2      |        Medhanit Abebe        | -0.015104352598219978  |
|   37   |      Seattle Police Department       |        Abed        |    George   |            Police Officer-Patrol            |    74.98    |      155958.4      |         George Abed          |  0.11132691628426016   |
|   38   |       Seattle Municipal Courts       |      Abe-Fava      |    Beryl    |   Information Technology Professional B BU  |    75.71    |      157476.8      |        Beryl Abe-Fava        | -0.023653049229094766  |
|   39   |            Seattle Center            |       Abejon       | Bryan-Peter |                    Usher                    |    26.92    | 55993.600000000006 |      Bryan-Peter Abejon      |  -0.10648198162401337  |
|   40   | Seattle Department of Transportation |     Abelhauser     |     Barb    |               Bridge Operator               |    41.56    |      86444.8       |       Barb Abelhauser        |  -0.0254948998952197   |
|   41   |       Seattle Public Utilities       |      Abellana      |  Mark Louis |                 Meter Reader                |     38.7    |      80496.0       |     Mark Louis Abellana      |  0.10736890004850304   |
|   42   |            Neighborhoods             |      Abellera      |  Francesca  |    Planning and Development Specialist II   |    57.31    |      119204.8      |      Francesca Abellera      |  -0.05048695405320221  |
|   43   | Seattle Department of Transportation |       Abels        |    Karen    |       Administrative Specialist II-BU       |    41.31    |      85924.8       |         Karen Abels          |  0.03977279834577652   |
|   44   |       Seattle Public Utilities       |       Abels        |    Steven   |        Environmental Field Specialist       |    48.28    | 100422.40000000001 |         Steven Abels         |  -0.07878120389627036  |
|   45   |  Finance and Administrative Service  |      Abenojar      |    Ester    |            Finance Analyst,Senior           |    60.55    |      125944.0      |        Ester Abenojar        |   0.1395320312749194   |
|   46   |       Seattle Public Utilities       |       Abera        |     Mulu    |     Management Systems Analyst,Assistant    |    48.31    |      100484.8      |          Mulu Abera          |  0.02733044979149331   |
|   47   |   Parks and Recreation Department    |       Abera        |     Bana    |              Recreation Leader              |    34.08    |      70886.4       |          Bana Abera          | -0.018562948049050686  |
|   48   |          Seattle City Light          |       Ablow        |  Elizabeth  |  Strategic Advisor 2, Utilities - L21C SCL  |    81.93    | 170414.40000000002 |       Elizabeth Ablow        |  0.08042609294806402   |
|   49   |      Seattle Police Department       |       Abraha       |   Ytbarek   |         Parking Enforcement Officer         |    37.18    |      77334.4       |        Ytbarek Abraha        |  0.07250463888555903   |
+--------+--------------------------------------+--------------------+-------------+---------------------------------------------+-------------+--------------------+------------------------------+------------------------+
Truncated to displaylimit of 50.

In [36]:
%config SqlMagic.displaylimit = 50

In [23]:
%%sql
select count(distinct("Job Title")) from wages

Running query in 'sqlite:///wages.db'

+------------------------------+
| count(distinct("Job Title")) |
+------------------------------+
|             1181             |
+------------------------------+

In [60]:
%%sql
select "Department", avg("Hourly Rate") as avg_wage, count(*) as num_interns from wages
where "Job Title" like "% intern"
group by "Department"
order by num_interns desc

Running query in 'sqlite:///wages.db'

+--------------------------------------+--------------------+-------------+
|              Department              |      avg_wage      | num_interns |
+--------------------------------------+--------------------+-------------+
| Seattle Department of Transportation | 25.98574074074074  |      54     |
|          Seattle City Light          | 26.594358974358975 |      39     |
|   Parks and Recreation Department    |  22.4074358974359  |      39     |
|       Seattle Public Utilities       |     26.9928125     |      32     |
|            Law Department            | 29.166666666666668 |      6      |
|    Sustainability and Environment    | 26.392500000000002 |      4      |
|    Planning and Community Office     | 25.96666666666667  |      3      |
|            Human Services            |       22.56        |      3      |
|        Legislative Department        |       22.56        |      2      |
|         Civil Rights Office          |       27.67        |      2      |
|      Seattle Police Department       |       27.67        |      1      |
|        Information Technology        |       22.56        |      1      |
|     Employees Retirement System      |       27.67        |      1      |
|     Construction and Inspections     |       22.56        |      1      |
+--------------------------------------+--------------------+-------------+

In [59]:
%%sql
select "Department", "Hourly Rate", "Job Title"
from wages
where "Job Title" like "% intern"
order by "Hourly Rate" desc

Running query in 'sqlite:///wages.db'

+--------------------------------------+-------------+------------------------------+
|              Department              | Hourly Rate |          Job Title           |
+--------------------------------------+-------------+------------------------------+
|            Law Department            |    32.47    |        Rule 9 Intern         |
|            Law Department            |    32.47    |     Rule 9 Legal Intern      |
|            Law Department            |    32.47    |         Legal Intern         |
|            Law Department            |    32.47    |        Rule 9 Intern         |
| Seattle Department of Transportation |    30.79    |   Student Engineer Intern    |
| Seattle Department of Transportation |    30.79    |   Student Engineer Intern    |
| Seattle Department of Transportation |    30.79    |   Student Engineer Intern    |
|       Seattle Public Utilities       |    29.46    |   Student Engineer Intern    |
|       Seattle Public Utilities       |    29.46    |   Student Engineer Intern    |
|          Seattle City Light          |    29.46    |   Student Engineer Intern    |
|       Seattle Public Utilities       |    29.46    |   Student Engineer Intern    |
| Seattle Department of Transportation |    29.46    |   Student Engineer Intern    |
|          Seattle City Light          |    29.46    |   Student Engineer Intern    |
|          Seattle City Light          |    29.46    |   Student Engineer Intern    |
|          Seattle City Light          |    29.46    |   Student Engineer Intern    |
|          Seattle City Light          |    29.46    |   Student Engineer Intern    |
|          Seattle City Light          |    29.46    |   Student Engineer Intern    |
|       Seattle Public Utilities       |    29.46    |   Student Engineer Intern    |
|       Seattle Public Utilities       |    29.46    |   Student Engineer Intern    |
|          Seattle City Light          |    29.46    |   Student Engineer Intern    |
|       Seattle Public Utilities       |    29.46    | Construction Engineer Intern |
|          Seattle City Light          |    29.46    |   Student Engineer Intern    |
|          Seattle City Light          |    29.46    |   Student Engineer Intern    |
|          Seattle City Light          |     29.3    |  Student Accountant Intern   |
|          Seattle City Light          |     29.3    |  Student Accountant Intern   |
| Seattle Department of Transportation |     29.3    |  Student Accountant Intern   |
|       Seattle Public Utilities       |    28.51    |   Student Engineer Intern    |
| Seattle Department of Transportation |    28.51    |   Student Engineer Intern    |
|       Seattle Public Utilities       |    28.51    |   Student Engineer Intern    |
|       Seattle Public Utilities       |    28.51    |   Student Engineer Intern    |
|       Seattle Public Utilities       |    28.51    |   Student Engineer Intern    |
| Seattle Department of Transportation |    28.51    |   Student Engineer Intern    |
| Seattle Department of Transportation |    28.51    |   Student Engineer Intern    |
| Seattle Department of Transportation |    28.51    |   Student Engineer Intern    |
| Seattle Department of Transportation |    28.51    |   Student Engineer Intern    |
|       Seattle Public Utilities       |    27.67    | Municipal Government Intern  |
| Seattle Department of Transportation |    27.67    | Municipal Government Intern  |
|          Seattle City Light          |    27.67    | Municipal Government Intern  |
|     Employees Retirement System      |    27.67    | Municipal Government Intern  |
| Seattle Department of Transportation |    27.67    | Municipal Government Intern  |
| Seattle Department of Transportation |    27.67    | Municipal Government Intern  |
| Seattle Department of Transportation |    27.67    | Municipal Government Intern  |
|          Seattle City Light          |    27.67    | Municipal Government Intern  |
|       Seattle Public Utilities       |    27.67    | Municipal Government Intern  |
|       Seattle Public Utilities       |    27.67    | Municipal Government Intern  |
|    Sustainability and Environment    |    27.67    | Municipal Government Intern  |
| Seattle Department of Transportation |    27.67    | Municipal Government Intern  |
|          Seattle City Light          |    27.67    | Municipal Government Intern  |
| Seattle Department of Transportation |    27.67    | Municipal Government Intern  |
|       Seattle Public Utilities       |    27.67    | Municipal Government Intern  |
+--------------------------------------+-------------+------------------------------+
Truncated to displaylimit of 50.

In [66]:
%%sql
select distinct("Job Title")
from wages
where "Job Title" like "% intern%"

Running query in 'sqlite:///wages.db'

+--------------------------------------------------------+
|                       Job Title                        |
+--------------------------------------------------------+
|                   High School Intern                   |
|                   Cooperative Intern                   |
|                Student Engineer Intern                 |
|              Municipal Government Intern               |
|               Student Accountant Intern                |
|            Municipal Government Intern W/S             |
|              Law Data Transparency Intern              |
|                     Rule 9 Intern                      |
|                  Rule 9 Legal Intern                   |
|                      Legal Intern                      |
| Nisqually Earthquake Anniversary Communications Intern |
|              Construction Engineer Intern              |
|                 Cooperative Intern W/S                 |
|                 Communications Intern                  |
+--------------------------------------------------------+

In [68]:
%%sql
select distinct("Job Title") as jobs, avg("Hourly Rate") as hourly, count(*)
from wages
group by jobs
order by hourly desc

Running query in 'sqlite:///wages.db'

+------------------------------------------------------+--------------------+----------+
|                         jobs                         |       hourly       | count(*) |
+------------------------------------------------------+--------------------+----------+
|           City Light General Manager & CEO           |       254.79       |    1     |
|              SPU General Manager & CEO               |       179.55       |    1     |
|                      Fire Chief                      |       179.55       |    1     |
|                 Seattle Police Chief                 |       179.54       |    1     |
|         Electric Utility Executive 3,Officer         | 171.07571428571427 |    7     |
|                     Executive 4                      | 141.46545454545455 |    33    |
|        Electric Utility Executive 3,Director         |      141.3425      |    4     |
|            Interim Chief Customer Officer            |       138.12       |    1     |
|                        Mayor                         |       130.93       |    1     |
|            Police Captain - Violent Crime            |       127.69       |    1     |
|           Police Captain - Permanent Night           |       127.69       |    3     |
|               Police Captain-Precinct                |       126.37       |    5     |
|             Electric Utility Executive 2             |       125.14       |    2     |
|                    Police Captain                    | 122.38666666666666 |    12    |
|               Police Captain - Traffic               |       121.59       |    1     |
|            Fire Chief,Deputy Admin-80 Hrs            |       118.62       |    4     |
|                     Executive 3                      |      115.3025      |    64    |
|        Executive Director and Chief Librarian        |       115.19       |    1     |
|          Assistant CTO, Business Solutions           |       114.99       |    1     |
|                   Hearing Examiner                   |       112.16       |    1     |
|                    City Attorney                     |       111.39       |    1     |
|               Code Compliance Director               |       110.06       |    1     |
|               Criminal Division Chief                |       109.87       |    1     |
|                 Civil Division Chief                 |       109.87       |    1     |
|          Director, Administrative Services           |       108.66       |    1     |
|         Investments/Debt Director,Assistant          |       108.47       |    1     |
|                    Chief of Staff                    |      107.785       |    2     |
|               Power Dispatcher,Senior                |       107.51       |    13    |
|                Police Lieutenant-CRG                 |       107.38       |    1     |
|              Director, Public Services               |       106.97       |    1     |
| Director of Employee Development, Equity & Belonging |       106.59       |    1     |
|                 Police Lieutenant-WC                 |     105.89625      |    16    |
|   Electrical Power Systems Engineer,Principal -Mrt   |       105.08       |    16    |
|   Director,Institutional and Strategic Advancement   |       104.87       |    1     |
|             Director, Employee Relations             |       104.81       |    1     |
|                     Executive 2                      | 104.75684210526316 |   133    |
|         Fire Battalion Chief-Administrative          |       104.11       |    1     |
|                  Police Lieutenant                   | 103.5886111111111  |    36    |
|                   Municipal Judge                    |       102.87       |    7     |
|              Investments/Debt Director               |       102.51       |    1     |
|                Power Supply Engineer                 |       101.66       |    2     |
|          Director of Inclusion & Belonging           |       101.59       |    1     |
|                    Power Marketer                    |       101.38       |    2     |
|    Protection and Control Electrician Crew Chief     |       99.71        |    2     |
|                   Power Dispatcher                   |       98.85        |    13    |
|     Electrical Power Systems Engineer,Principal      |       97.91        |    9     |
|              Fire Chief,Deputy-91.4 Hrs              |       97.47        |    4     |
|             Fire Battalion Chief-80 Hrs              |       96.85        |    1     |
|                 Land Use Supervisor                  |       96.69        |    1     |
|        Electrical Power Systems Engineer-Mrt         | 96.64999999999999  |    17    |
+------------------------------------------------------+--------------------+----------+
Truncated to displaylimit of 50.